/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BotaoVisualizacaoAtividade;

import BotaoEdicaoAlunos.AcaoBotao;
import controllers.models.StudentController;

/**
 *
 * @author Fatec
 */
public class PainelComVisualizacao extends javax.swing.JPanel {

    public static AcaoBotao getAcaoBotao2() {
        return acaoBotao2;
    }

    public static void setAcaoBotao2(AcaoBotao acaoBotao2) {
        PainelComVisualizacao.acaoBotao2 = acaoBotao2;
    }

    public static AcaoBotao getAcaoBotao3() {
        return acaoEdit;
    }

    public static void setAcaoBotao3(AcaoBotao acaoBotao3) {
        PainelComVisualizacao.acaoEdit = acaoBotao3;
    }

    public static AcaoBotao getAcaoBotao4() {
        return acaoDelete;
    }

    public static void setAcaoBotao4(AcaoBotao acaoBotao4) {
        PainelComVisualizacao.acaoDelete = acaoBotao4;
    }

    /**
     * Creates new form PainelComVisualizacao
     */
    public PainelComVisualizacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        jTextField1.setText("Tareafa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 165, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acaoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoEditActionPerformed
     
    }//GEN-LAST:event_acaoEditActionPerformed

    private void acaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoDeleteActionPerformed
    }//GEN-LAST:event_acaoDeleteActionPerformed

    private void acaoBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoBotao2ActionPerformed
        // TODO add your handling code
    }//GEN-LAST:event_acaoBotao2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
