// public class FXMLDocumentController extends App{

//     public class FXMLDocumentController implements Initializable{
    
//     @FXML
//     private Button button;

//     @FXML
//     private Label label;

//     @Override
//     public void start(Stage stage) throws Execption{
//         Parent root = FMXLLoader.load(getClass().getResource("FXMLDocument.fxml"));

//         Scene scene = new Scene(root);

//         stage.set$cene(scene);
//         stage.show();
//     }
    

//     // Colocando a imagem em um botão
//     //A imagem deve estar na mesma pasta para funcionar
//     //Image image = new Image(getClass().getResourceAsStream("example.png"));
//     //buton1.setGraphic(new ImageView(image));

//     //Ação ao clickar no botão
//     buton1.setOnAction(ActionEvent e) ->{
//         label.setText("Funfou");
//     }

// }
// }