/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BotaoEditarAtividade;

import javax.accessibility.AccessibleIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import BotaoEdicaoAlunos.AcaoBotao;
import controllers.models.AssignmentController;
import controllers.models.StudentController;
import dao.AssignmentDAO;
import gui.ClienteGUI;
import models.Assignment;

/**
 *
 * @author Fatec
 */
public class PainelComEdicao extends javax.swing.JPanel {

    // public static AcaoBotao getAcaoBotao2() {
    //     return acaoBotao2;
    // }

    // public static void setAcaoBotao2(AcaoBotao acaoBotao2) {
    //     PainelComVisualizacao.acaoBotao2 = acaoBotao2;
    // }

    // public static AcaoBotao getAcaoBotao3() {
    //     return acaoEdit;
    // }

    // public static void setAcaoBotao3(AcaoBotao acaoBotao3) {
    //     PainelComVisualizacao.acaoEdit = acaoBotao3;
    // }

    // public static AcaoBotao getAcaoBotao4() {
    //     return acaoDelete;
    // }

    // public static void setAcaoBotao4(AcaoBotao acaoBotao4) {
    //     PainelComVisualizacao.acaoDelete = acaoBotao4;
    // }

    /**
     * Creates new form PainelComVisualizacao
     */

    public Assignment assignment;

    public PainelComEdicao(Assignment assignment) {
        this.assignment = assignment;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AtividadeNomeCampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DataInicioCampo = new javax.swing.JTextField();
        DataFimCampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NotaCampo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        FecharBotao = new BotaoEdicaoAlunos.AcaoBotao();
        SalvarBotao = new BotaoEdicaoAlunos.AcaoBotao();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Nome da atividade");
        AtividadeNomeCampo.setText(this.assignment.getName());

        jLabel3.setText("Data de Início:");
        DataInicioCampo.setText(this.assignment.getDate_assigned());

        jLabel4.setText("Data de Fim:");
        DataFimCampo.setText(this.assignment.getDate_due());

        jLabel5.setText("Nota Máxima:");
        NotaCampo.setText(String.valueOf(this.assignment.getMax_grade()));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Descrição da atividade");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(this.assignment.getDescription());
        jScrollPane1.setViewportView(jTextArea1);

        FecharBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/fechar.png"))); // NOI18N
        FecharBotao.setToolTipText("");
        FecharBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharBotaoActionPerformed(evt);
            }
        });

        SalvarBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/salvar.png"))); // NOI18N
        SalvarBotao.setToolTipText("");
        SalvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(AtividadeNomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DataFimCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(DataInicioCampo)
                            .addComponent(NotaCampo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(SalvarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FecharBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FecharBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AtividadeNomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DataInicioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(SalvarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DataFimCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NotaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acaoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoEditActionPerformed
     
    }//GEN-LAST:event_acaoEditActionPerformed

    private void acaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoDeleteActionPerformed
    }//GEN-LAST:event_acaoDeleteActionPerformed

    private void acaoBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoBotao2ActionPerformed
        // TODO add your handling code
    }//GEN-LAST:event_acaoBotao2ActionPerformed

    private void FecharBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharBotaoActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja parar de editar? \nVocê perderá qualquer edição feita", "Editar atividade", JOptionPane.YES_NO_OPTION) == 0){
            AssignmentController.toggleAssignmentView(null);
        }
    }//GEN-LAST:event_FecharBotaoActionPerformed

    private void SalvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBotaoActionPerformed
        AssignmentController.updateAssignment(this);
    }//GEN-LAST:event_SalvarBotaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AtividadeNomeCampo;
    public static javax.swing.JTextField DataFimCampo;
    public static javax.swing.JTextField DataInicioCampo;
    private BotaoEdicaoAlunos.AcaoBotao FecharBotao;
    public static javax.swing.JTextField NotaCampo;
    private BotaoEdicaoAlunos.AcaoBotao SalvarBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
